spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/freeBoardV2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

logging.level:
  org.hibernamte.sql: debug
